steps:
  #unit test cases
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
#sonarqube code coverage 
- name: 'gcr.io/niveus-cici-demo/sonar-scanner:latest'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login=e5f2827bf0321743ddfa267bd90d0ac0a4273798'
  - '-Dsonar.projectKey=frontend12'
  - '-Dsonar.organization=demo-niveus'
  - '-Dsonar.sources=.'
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveus-cici-demo/frontend', '--build-arg', 'URL=${TAG_NAME}', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveus-cici-demo/frontend']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','frontend', '--platform=managed', '--image', 'gcr.io/niveus-cici-demo/frontend', '--region', 'us-central1', '--quiet']
