steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveus-cici-demo/cloud', '--build-arg', 'URL=${TAG_NAME}', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveus-cici-demo/cloud']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','cloud','--image', 'gcr.io/niveus-cici-demo/cloud', '--region', 'us-central1', '--quiet']
