steps:
  #sonar scanner
 - name: 'gcr.io/niveusgcp/sonar-scanner:latest'
   args: ['-Dsonar.host.url=34.67.147.127:9000', '-Dsonar.login={admin}', '-Dsonar.projectKey={blog}']
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveusgcp/cloud', '--build-arg', 'URL=${TAG_NAME}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveusgcp/cloud']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','cloud','--image', 'gcr.io/niveusgcp/cloud', '--region', 'us-central1', '--quiet']
