apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
    env: production
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 31008
    protocol: TCP